version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    environment:
      APP_BUNDLER_VERSION: 2.2.25 # This is how the Orb can choose a Bundler version without a Gemfile.lock
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps:
          with-cache: false # We run without a Gemfile.lock, and must therefore not attempt to cache, otherwise the Orb fails.
          # bundler-version: 2.2.16 # This can not be used, since the Orb has bugs.
          path: experimental # This must used, since if the default value vendor/bundle is used, a Gemfile.lock is assumed, leading to failures.
      - ruby/rspec-test

