version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    environment:
      APP_BUNDLER_VERSION: 2.2.16
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.2.16
          with-cache: false
          path: experimental
      - ruby/rspec-test

